version: '2'
services:
  nginx:
    build: etc/docker/development/nginx
    depends_on:
      - fpm
    ports:
      - "8080:80"
    volumes:
      - "$PWD:/app"

  fpm:
    build: etc/docker/development/fpm
    container_name: app_dev_fpm
    depends_on:
      - mysql
    ports:
      - "2222:22"
      - "9000:9000"
    volumes:
      - "$PWD:/app"
      - ~/.ssh:/root/.ssh

  mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdev-api
    volumes:
      - db_data:/var/lib/mysql



  code_volume:
    image: busybox
    volumes:
      - .:/app
volumes:
  db_data:
